### PR TITLE
Lolivo final project

### PR DESCRIPTION
**Pull request by Lolivo**
My final project is finally finished!!!
Page here 
https://lolivo.github.io/
W3 School Bootsrap Gallery Template was used in the making of this Gallery

### CODE REVIEW

**Comment by lminks** [comment]
Looks good. Two things, though: the meme luck generator doesn't ever seem to be able to return a 10 out of 10 (though it does do a 0 out of 10), and the audio file is referencing something local on your machine instead of a public file, so it doesn't play.

**Comment by MCastro46** [comment]
Listen here, you are now the Mememan.   I went to lookat memes and click on them, but they all returned me to the top. Is that intentional? But uh. I stayed for the memes.

**Comment by JacobDanger** [comment]
I like the aesthetic and the music is a major plus. Great job!

**Comment by jnorris18** [comment]
Awesome website, I can tell you put a lot of work into this to have all this content. Looks awesome hope you get an A.

**Comment by jriosrodriguez** [comment]
Like they indicated before, when you click on a meme, the page returns to the top and the image in the Ancient Aliens meme didn't load,. However, excellent page HAHAHA I like it. Great job!

**Comment by hectorsector** [comment]
Awesome song, @Lolivo! I started looking at your project and put my computer away, when I came back the song was playing and I thought to myself, *where's that awesome song coming from?*. So thanks for that!

I think the web site turned out great. The random number generator at the bottom didn't actually send me to a meme, but maybe I'm not using it correctly. 

👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
