### PR TITLE
Marxspawn final project

### PR DESCRIPTION
**Pull request by marxspawn**
# Marxspawn's Final Project
- I am starting this pull request to get some feedback on how everything looks. 

- Please feel free to add any suggestions to what I have here.
  - How easy were you able to find my [site](https://marxspawn.github.io/webBasedJavaDemo/) ?
  - Was there any difficulty navigating through the site or repo?

### CODE REVIEW

**Comment by lucianoh** [comment]
I had no problem accessing the site through the link you provided. Navigating through it was fairly simple. The live coding portion was a cool thing to include. Great job!

**Comment by marxspawn** [comment]
@lucianoh Thanks, I'm not sure how to see other peoples codes. Do you know if we sync their project then view from desktop?

**Comment by Javier-of-the-Rich-Port** [comment]
I had no problem navigating to you site, all buttons worked correctly, only issue I ran into was that it was off center for me, hanging to the left side. I 'm sure if you were trying to center it or not.

**Comment by marxspawn** [comment]
@Javier-of-the-Rich-Port Thanks for the feedback.

I would like to know what you viewed the page with. 

I did not try to make the page too mobile friendly ... Yet :grimacing:

**Comment by StephanNears** [comment]
I really enjoyed the shadow aesthetic you put on it. It doesn't look to off-kilter to me. It my just be me though. I did Firefox, Ie and Chrome.

**Comment by Javier-of-the-Rich-Port** [comment]
@marxspawn I viewed the page on my desktop with a 1920x1080 resolution. I'll try to post a screen shot for you if you think it's help

**Comment by marxspawn** [comment]
My MacBook has the retina display 2560x1600 but its only a 13" screen. 

I just uploaded a whole new layout and for some reason it looks completely different when viewing from GitHub pages than it does when I load it from my dev folder on the laptop.

**Comment by jmasterson5** [comment]
it was fairly easy to use nothing to hard and it seem to run properly

**Comment by marxspawn** [comment]
@hectorssector 
### Thank you 
-  The live code portion is from a project here on GitHub called [CodeMirror](http://codemirror.net/) that is very widely used.
-  I did give credit in devel folder README.md.
-  I will add a comment in the .html portion of it as well.

**Comment by rbowser5** [comment]
Dang that website was polished! I really liked the page, very cool seeing how you coded it looking at the elements. I run on a 27" 1440p screen and it honestly looked perfect, but I'm not sure how it would run on other monitors.

**Comment by Mikedaris94** [comment]
Really like how you placed my link in the word site very creative and your site looks great!

**Comment by Jordan-Hosein** [comment]
Pretty cool! I actually used it to test some code for my own project, haha.

**Comment by mdean19** [comment]
Wow dude this is awesome, didn't know you could do this :)

**Comment by AntoineDS** [comment]
@marxspawn That was great. Your creativity took it to the next level! All the button worked as well.

**Comment by marxspawn** [comment]
@AntoineDS , @mdean19 , @Jordan-Hosein , @Mikedaris94 , @rbowser5 

- Thanks everyone I appreciate the commets
- I reworked the visual look of the page for fun and redid some of the codes 

Let me know what you guys think

**Comment by hectorsector** [comment]
@marxspawn 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
