### PR TITLE
AntoineDS-final-project

### PR DESCRIPTION
**Pull request by AntoineDS**
A Few questions for my website. https://antoineds.github.io/final-project/

1. Does the website scroll properly on a cell phone?
2. Do the images in within the programming language section scale to a mobile device?
3. Does the contact form work properly?

### CODE REVIEW

**Comment by mariadodoll** [comment]
1. Yes your website scrolls properly on a cell phone. 
2. Yes the images in within the programming language section scale to a mobile device.
3. Yes the contact form works properly. Overall great job.

**Comment by AntoineDS** [comment]
The mail server is still not working the proper way I will continue to work on this.

**Comment by Snack-Pack** [comment]
Everything seems fine to me with the exception of your mail server which you already seem to be aware of,

**Comment by hectorsector** [comment]
Very pretty theme, @AntoineDS. I was also unable to use your contact form.

Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
