### PR TITLE
Javier of the rich port s final project

### PR DESCRIPTION
**Pull request by Javier-of-the-Rich-Port**
This is my modified tic tac toe game.

For feed back I'd like to know if you encounter any bugs or issues and what you think of the difficulty levels.

Should I adjust any of them? Can you beat hard easily or does it stump you?

### CODE REVIEW

**Comment by marxspawn** [comment]
Game play is spot on. No bugs encountered. I like the display and simplicity. excellent job 👍

**Comment by lucianoh** [comment]
The AI is really good One little glitch I encountered was when the opponent placed an "O" down you could click the same spot and place an "X" over it. Besides that the game was really fun and well made. Awesome job!

**Comment by marxspawn** [comment]
@lucianoh Thats funny, I played the game quite a few times and it counters the moves absolute...

I  didn't think to Cheat it 😜 

I only kid, thats true game testing though 👍 

One aspect to make things different would be having the AI go first if you lose a game

**Comment by kzeng16** [comment]
It's pretty well made, but how do I select the difficulty?
Placing first on the bottom left corner, then the middle right, bottom right, and then at the bottom middle always guarantees a win.

**Comment by Javier-of-the-Rich-Port** [comment]
Thanks for the feed back everyone.

@lucianoh thanks for finding this for me, I'll look into it but it'll probably take me a bit of time to fix

@kzeng16 You need to press on the buttons labeled with difficulties, I added this to the readme instructions,
As for the guarantee win, tic tact toe is a solved game, if I made the AI any smarter you could never win at the highest difficultly so I left an out for people to win. Do you think I should change this?

**Comment by SPierre30** [comment]
Lmao. I like your game xD. It's simple and pretty straight forward, I don't really see any noticeable mistakes. Good job!

**Comment by hectorsector** [comment]
Linking to your original issue #11

**Comment by Javier-of-the-Rich-Port** [comment]
I added a difficulty notification but am having trouble getting gitpages to create a site, I have a repository and an index.html file but it does not want to create the page

**Comment by jenny0325** [comment]
@Javier-of-the-Rich-Port Great job, nicely executed.

**Comment by hectorsector** [comment]
@Javier-of-the-Rich-Port Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
