### PR TITLE
KaidyCEThomas-final-project-submission

### PR DESCRIPTION
**Pull request by KaidyCEThomas**
Implementation Phase of blog site.

Please visit my first blog post here: http://eatsiprepeat.blogspot.com/

Let me know your overall thoughts. I deviated from my original plans so any feedback is welcomed.

Thank you!

### CODE REVIEW

**Comment by jenny0325** [comment]
I thought your blog was nice!

**Comment by marxspawn** [comment]
Very nice... Now I'm hungry :yum:
They layout is very nice. 
The font type was a bit hard to see at first, then I turned the brightness up on my laptop lol.
I would like to know how you did the image carousel that looks really good. I have been trying to do something like that on a page I am working - without generating it through a web publishing app.
Good job 👍

**Comment by orlandogivens** [comment]
wow pretty good site. How did you get your images in the background? I was trying to do it also but could not figure it out.

**Comment by orlandogivens** [comment]
wow pretty good site. How did you get your images in the background? I was trying to do it also but could not figure it out.

**Comment by hectorsector** [comment]
@KaidyCEThomas thanks for the submission. I see something that was create in Blogpost, but unfortunately since it's on an external site I cannot see the source code that you programmed. If you would like to email me directly with your source code I can grade it based on that.

**Comment by hectorsector** [comment]
Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
