### PR TITLE
Jbrady22 s final project

### PR DESCRIPTION
**Pull request by JBrady22**
I would love some feedback on what you think of it. what you would change? stuff like that

### CODE REVIEW

**Comment by StephanNears** [comment]
I gotta say that it works and all, but it's a little hard on the eyes. I understand it's Holiday theme, but maybe adding in a background image or a less intense color would help.

**Comment by JBrady22** [comment]
@StephanNears yeah i realized that but i had to add some css elements but i was gonna wait to see if maybe it was just me but since you said it i will change it.

**Comment by marxspawn** [comment]
@JBrady22 
The coded portion works good, no problems there. 

I agree with @StephanNears, it is a little hard on the eyes.

Soemthing thing I have learned through web designing is certain color combos cannot be viewed by the visually impaired, and I believe red on solid green is the main one. It can appear as a blank page to someone with color blindness. 
Designing a stylesheet from scratch can be very time consuming, I would suggest finding a page layout you like and use that stylesheet. Then change your HTML's #ID/.Class tags to help with the flow. 
Good luck with the project

**Comment by jmasterson5** [comment]
the sight worked really well just a little hard on the eyes try and make it more view able by others so it doesn't just lean towards your prefrances

**Comment by hectorsector** [comment]
Linking to your original issue: #13

**Comment by hectorsector** [comment]
@JBrady22 Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
