### PR TITLE
Aalevane final project

### PR DESCRIPTION
**Pull request by aalevane**
My project is available <a href="https://aalevane.github.io">here</a>. Let me know if there's anything you would change or if you have any issues with the site. And don't forget to hover over the images in the <a href="https://aalevane.github.io/work.html">gallery</a> to see them better! :)

### CODE REVIEW

**Comment by mirenagreen** [comment]
The website looks great! The only thing I would say is that the image size in the gallery is big. It's hard to view the images at the bottom without accidentally selecting another image.

**Comment by radicalpharaoh** [comment]
Awesome gallery work! Just like the critique above, the images are hard to view. But other than that, good job!

**Comment by aalevane** [comment]
I see what you guys mean, I'll work it now! Thanks for the suggestion.

**Comment by hectorsector** [comment]
@aalevane I'm so impressed with this theme that you built from scratch. I hope you'll consider sharing it with others. There's a few sites out there for sharing themes people have built. It's beautiful, you should feel very proud of yourself 😄 

👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
