### PR TITLE
Magdiel final

### PR DESCRIPTION
**Pull request by MCastro46**
Please copy and paste this Full link into your web browser to take a gander!

github-windows://openRepo/https://github.com/cop1000/final-project?branch=Magdiel-Final&filepath=index.html

### CODE REVIEW

**Comment by jnorris18** [comment]
hey man do you think you could help me out?

**Comment by MCastro46** [comment]
Sure, actually, give me a moment, my link isn't working either, so i need to fix it.

**Comment by MCastro46** [comment]
are you on the gitter chat? pm me

**Comment by Jordan-Hosein** [comment]
Looks great! I gotta get back into this game since I can afford it now.
~Click on his twitch link to go follow him if you have twitch~

**Comment by jnorris18** [comment]
got it thank you anyways

**Comment by aalevane** [comment]
The link isn't working for me, are you still trying to figure it out? I think for Github Pages to work you _have_ to upload your work into your "your-username.github.io" repo, so you would have to overwrite the old assignment we did earlier in the class. I remember it mentioning that they only give you one website to host so I think that's why it might not be working. I uploaded my assignment to my dev folder in my final-project branch and also onto my aalevane.github.io repo/Github Pages so classmates can see my project with a single click.

**Comment by marxspawn** [comment]
You have to host it from your own repo. load the files and hit the settings button at the top of your GitHub home page, it will generate it from there. They will  host pages for every project to start on here. I still have my first project up from this class along with my final

**Comment by hectorsector** [comment]
@MCastro46 some of the advice from @aalevane and @marxspawn may be useful.

I graded the site as is, just wanted to also give you some feedback if you plan on updating this site after the class is over:
- I liked that you used a responsive theme 👍 
- The artwork was nice, just ensure that you give credit, as well as credit to the authors of the theme
- It seems like you navigated the logistics of theme pretty well, however there were some posts that were not reachable for me.
- The contact form was nice, but I imaged it would be a comment section. Are you getting the submissions posted by people? 

👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
