### PR TITLE
Snack-Packs Final Project

### PR DESCRIPTION
**Pull request by Snack-Pack**
What are your thoughts On the overall look?

Does the calculator work for you?

What could I  have done to make it better?

https://snack-pack.github.io/Calorie/

### CODE REVIEW

**Comment by kzeng16** [comment]
The calculator works and the design of the website is very neat. Nice job!

**Comment by JacobDanger** [comment]
Cool looking calculator! I'm digging the layout

**Comment by radicalpharaoh** [comment]
Awesome calculator and nice spin on what you wanted to do. Great!

**Comment by orlandogivens** [comment]
That's pretty cool man. Good job. It works good when I tried it I wouldn't change anything.

**Comment by mariadodoll** [comment]
Awesome I liked the calculator and the overall look. I liked the background that you selected. The calculator worked for me. I really like the entire concept so I have no suggestions on improvement.

**Comment by marxspawn** [comment]
Page looks really nice

Code works good

Good job 👍

**Comment by hectorsector** [comment]
@Snack-Pack please check your email.

**Pull request closed without merging**
