### PR TITLE
Final Project

### PR DESCRIPTION
**Pull request by jnorris18**
https://jnorris18.github.io/jnorris18/

had trouble with the github link, is everyone able to access it correctly?
is it too hard to read the website with the background being so bold?

### CODE REVIEW

**Comment by mirenagreen** [comment]
Hi @jnorris18 the link is working for me. The only thing I would change is the font-size for the bullet points.

**Comment by jjyates4** [comment]
I like how you organized everything and the images are the perfect size for each player.

**Comment by ZPeterson2** [comment]
The link works great. Just hard to see some of the information because of size and layout.

**Comment by hectorsector** [comment]
@jnorris18 Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
