### PR TITLE
kzeng16's Final Project

### PR DESCRIPTION
**Pull request by kzeng16**
Hello, just wanted to see if the page works well for everyone.
Please let me know if there's anything I should add or improve.
https://kzeng16.github.io/

### CODE REVIEW

**Comment by marxspawn** [comment]
## Looks fantastic. 

## The randomizing code you programmed in itself is awesome. 

# Excellent Job!

I give you the old [Siskel & Ebert](https://en.wikipedia.org/wiki/At_the_Movies_(U.S._TV_series)) 👍 👍

**Comment by StephanNears** [comment]
That works perfectly. I was really impressed that you put all the Pokemon in there, up to Gen 6! The code was neat  and I enjoyed the variety. I don't really have any changes I believe you could make.

**Comment by JBrady22** [comment]
This was great. i enjoyed seeing which Pokemon i would randomly get. my only comment would be some how making it scale small to where the generator fit on the whole screen. for me i had to scroll down to see the other half of the page. Overall it might scale differently for other people but some people not see the other options of Pokemon that they have to scroll down for.

**Comment by hectorsector** [comment]
Linking to your original issue: #23

**Comment by Lolivo** [comment]
This is really good stuff! My only suggestion is to change the way it's organized so its a bit more balanced across the screen without so much empty space.

**Comment by mdean19** [comment]
This is pretty cool :) got Aerodactyl as one of my six, which is my favorite :)

**Comment by AntoineDS** [comment]
@kzeng16  I did not know we had this many pokemon it was a great experience. I wish you could like on the pokemon and know more about them like a pokedex.

**Comment by JacobDanger** [comment]
3 rock pokemon? 0/10 literally unusable

(seriously tho that's pretty tight)

**Comment by hectorsector** [comment]
@kzeng16 Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
