### PR TITLE
Mikedaris94 Final Project

### PR DESCRIPTION
**Pull request by Mikedaris94**
Please let me know if you see everything that should be displayed.

https://mikedaris94.github.io/Mike-Daris-Final-Project/

### CODE REVIEW

**Comment by kzeng16** [comment]
Everything is looking good except for this "a name="End">" at the bottom of the page above your timeline picture.

**Comment by mariadodoll** [comment]
Everything works and looks great.

**Comment by jnorris18** [comment]
Looks awesome man, I am super excited for the new game too. Everything looks great, maybe you could have centered the pictures to make it look a little more neat but that is just my opinion. Overall great job hope you get an A.

**Comment by Snack-Pack** [comment]
It works great and I like the look

**Comment by radicalpharaoh** [comment]
That's awesome! My friend always tells me to play KH. I might give it a try because of you!

**Comment by hectorsector** [comment]
@Mikedaris94 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
