### PR TITLE
StephanNears final project

### PR DESCRIPTION
**Pull request by StephanNears**
Should I add more Pokemon and Questions?

Should I figure out a different way of keeping scores and such?

All feedback is welcome.

### CODE REVIEW

**Comment by Javier-of-the-Rich-Port** [comment]
I can't seem to open your project as a webpage, it just brings up the file with the HTML code, I don't think it's creating the site

**Comment by lucianoh** [comment]
Your quiz was pretty cool. I really liked how you managed to incorporate the pokemon theme into the site. I would recommend adding just a few more questions, but aside from that great job. Also my pokemon was Lucario.

**Comment by Javier-of-the-Rich-Port** [comment]
I got it to work. The music was a nice touch.

For a quiz it felt like it had to few questions but you did show you knew how to code it so well done.

**Comment by marxspawn** [comment]
## Nice work @StephanNears 

👍 

I like how the code is generated. pretty cool. 


- I would like to make a suggestion:
  - The view from my MacBook looks a little stretched. 
  - I played around with the view from my end and would like to show you an option on the visual end of things 

[PokemonQuizAlt.html.zip](https://github.com/cop1000/final-project/files/644297/PokemonQuizAlt.html.zip)

Check it out and let me know what you think. 
:octocat:

**Comment by StephanNears** [comment]
I really enjoy the changes you made, I think I made it too wide when I first started. Also the Coloring is much easier on the eyes.

**Comment by JBrady22** [comment]
@StephanNears i think the quiz was great. it looked properly sized on my screen. Also on the question Where would they find you? there was some coding off because one of the answers is not under the question and there is a p> for no reason. just thought you should know.

**Comment by Cjwilliams36** [comment]
I believe lucianoh said there was pokemon soundtrack but I couldn't hear anything on my end so i don't know if you changed that. But other than that great job :)

**Comment by jmasterson5** [comment]
really great job I like the Pokemon theme especially do to me being a Pokemon fan anyway

**Comment by hectorsector** [comment]
Linking to your original issues #9

**Comment by StephanNears** [comment]
I made most of it up on my own. Just went through my textbook and found the radio buttons and worked it from there.

**Comment by rbowser5** [comment]
I give this 0/10 because I got Gengar. But seriously good job! Everything worked really smoothly.

**Comment by AGuerraDumas** [comment]
The website was pretty cool, really liked that you added the pokemon theme. I think you should've had more answer for each question, and give them different values.

**Comment by Jordan-Hosein** [comment]
Amazing job! 
Very enjoyable and it was funny watching my mom call every pokemon that came up Pikachu.

**Comment by hectorsector** [comment]
@StephanNears Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
