### PR TITLE
Cjwilliams36 Final Project

### PR DESCRIPTION
**Pull request by Cjwilliams36**
Pretty straight forward to use.
If there's anything that can be improved upon let me know. Or if there's any additions you'd want to see. 

https://goo.gl/95hkWc<--shortened url for easy viewing

### CODE REVIEW

**Comment by Javier-of-the-Rich-Port** [comment]
But I don't wanna be fireembryo.

Neat site but after I get the name I get directed too https://htmlpreview.github.io/? is this a problem with your code or the URL shortening?

Also if you don't enter a birthday it just returns Na. Maybe you could have it ask for an imput if you click without entering any information or make the get nickname button unclickable until then

**Comment by hectorsector** [comment]
Linking to your original issue: #cj

**Comment by Lolivo** [comment]
GENERAL BARCODE REPORTING IT, I LOVED IT SO MUCH,perhaps some more 8 bit text to improve it, but I like the aesthetic alot

**Comment by Mikedaris94** [comment]
Its quite different from all the other ones I view lol! I like it!! xD!

**Comment by mdean19** [comment]
Haha I got PrivateSky, no idea why I found it funny but I like how the site is setup! :)

**Comment by AntoineDS** [comment]
Great @Cjwilliams36  the only thing I would change is the page redirection.

**Comment by JacobDanger** [comment]
Caught me off guard with this one. Simple, but really neat!

**Comment by hectorsector** [comment]
@Cjwilliams36 Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
