### PR TITLE
Mirenagreen final project

### PR DESCRIPTION
**Pull request by mirenagreen**
➡️ [My project](https://github.com/cop1000/final-project/tree/mirenagreen-final-project/devel)
Could you get the results correctly?
What did you think about the design?

I was initially planning on creating a project more focused on the design. However I ended up spending too much time trying to figure out some mistakes on the coding that was preventing the results from generating properly, so I had to focus more on making sure my project would work. 

Please feel free to give any suggestions!

### CODE REVIEW

**Comment by KaidyCEThomas** [comment]
I got Magic Kingdom! This project definitely shows how thoughtful you were in your approach, timeline execution. Nice work lady!

**Comment by marxspawn** [comment]
1 question?.. Ok, 2 questions...
How did you know I was wearing a Pirate Hate and glass slippers? :flushed: Did I leave my camera app on again? 😮 

You did good job on this
I enjoyed the comical aspect of it and the generated answers very well
👍

**Comment by ZPeterson2** [comment]
Great Job! I got the results Animal Kingdom, which is my favorite park. So your quiz is pretty accurate.

**Comment by hectorsector** [comment]
@mirenagreen Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
