### PR TITLE
Jordan hosein final project

### PR DESCRIPTION
**Pull request by Jordan-Hosein**
https://jordan-hosein.github.io/Jordan-Hosein-Final-Project.github.io/

To use the calculator:
 1. Select the checkbox for one of the two rockets.
 2. Pick one planet from the dropdown box.
 3. Click in the blank box.
 4. Continue selecting different planets to see additional calculations for that rocket,

To calculate using the other rocket:
1. Uncheck the previous rocket.
2. Select the checkbox for the new rocket.
3. Pick one planet from the dropdown box. 
4. Click in the blank box.
5. Continue selecting different planets to see additional calculations for that rocket.

### CODE REVIEW

**Comment by hectorsector** [comment]
Linking to your original issue #16

**Comment by Javier-of-the-Rich-Port** [comment]
So your calculator has the following problems.

Will not work unless the boxes above the drop down list are check off _before_ selecting a rocket or planet, checking the boxes afterward does not calculate either.

There is no indication that the boxes need to be checked.

Both drop down list displace the same choices for me in both lists, listing the planets but no rockets, despite the top list being labeled SLS for space launch system.( I.E. both list displayed wolf1061c keplar422b ect.)

**Comment by Lolivo** [comment]
Pretty cool planets and stuff, the calculator didn't work for me either :_(

**Comment by MCastro46** [comment]
going based on my love for astronomy,  i enjoyed the calculator the most, it seems going based off of previous comments, its now working good going!

**Comment by jenny0325** [comment]
@Jordan-Hosein I liked it.

**Comment by KaidyCEThomas** [comment]
I was really looking forward to this and I love the results. Apart from the calculator issues, the aesthetics and  follow through are show in your work. Great job!

**Comment by hectorsector** [comment]
@Jordan-Hosein 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
