### PR TITLE
lucianoh's final project

### PR DESCRIPTION
**Pull request by lucianoh**
Do all parts of the site work ok?

Is there anything I could improve upon?

What are your overall thoughts on my project?

### CODE REVIEW

**Comment by marxspawn** [comment]
### Artwork is great and I like the background on characters.

 I have never played, but I know the game itself has had a huge following as far back as I can remember _"The N.E.S. days"_ 👴 
 
Suggestions:
  - Something that could have made it a lot easier on you and saved a lot of repetitive typing (or copy/paste) 😝 
    -  Add a stylesheet 
    - Then link the .class and #id tags from there

  - Visually
    - The `<p>` elements appear floated far right when viewed from my MacBook (Safari and Firefox)
 and would be the only corrections I could suggest.

But overall, it looks good.

**Comment by lucianoh** [comment]
Thanks for the feedback @marxspawn

**Comment by Javier-of-the-Rich-Port** [comment]
Great site, reminded me I should go replay this games soon. as for feedback.

1) On the homepage the comment box was stuck  to the left side, not sure if it's supposed to be there or centered.

2) the boxes with descriptions of the character were all the same size even if some boxes had way more text then others which made them look odd, have you tried or thought about making the boxes size based around the amount of text?

**Comment by JBrady22** [comment]
@lucianoh i viewed your site and it looks great. my only comments was the comments box on the homepage was too small and that on the individual pages the boxes with information were too big. if you shrunk those down i think people will not have to scroll down as far t view all of the content. but overall great job.

**Comment by AGuerraDumas** [comment]
This is a really cool website, it makes me want to play Final Fantasy again. I really like the layout of the Home Page.

**Comment by hectorsector** [comment]
@lucianoh thanks for the early submission! I'm linking to your original issue: #19.

I have a few recommendations to get the best score possible:
- Make sure everything goes into a Bootstrap container. Currently all your content appears off the page for me and does not resize with the window.
- The comment section is some great use of JavaScript, but it's all stored locally for me. Can you look into embedding something that will allow you to grab the comments off the server? Something like [Disqus](https://disqus.com) might work. 
- Publish your site somewhere so it's easily accessible -- I'm happy to checkout your branch directly but it's more fun when you can share it with people as a whole. Consider using GitHub Pages like we did previously.

**Comment by hectorsector** [comment]
@lucianoh Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
