### PR TITLE
mariadodoll-Final-Project

### PR DESCRIPTION
**Pull request by mariadodoll**
Can you view the video that I added to the website?
Are you able to see the images that I have attached?
Do you like the layout of the font and images?

Here is the blog that I created.
https://mariadodoll.github.io/Herbalogic/

### CODE REVIEW

**Comment by jnorris18** [comment]
Good job creating this webpage. It is very informational and the youtube video is a nice extra to the page. Make sure you create some questions for us to answer so you get a 100%.

**Comment by mirenagreen** [comment]
Hi @mariadodoll your website is running correctly. And yes I can see the pictures and the video 👍

**Comment by Snack-Pack** [comment]
the website works fine and looks great.

**Comment by hectorsector** [comment]
@mariadodoll I didn't see any JavaScript on your site. 
Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
