### PR TITLE
Jomarm92x's final project

### PR DESCRIPTION
**Pull request by Jomarm92x**
Scientific calculator! Took some references from some of the other calculator apps and its not perfect but I'm working on it.

### CODE REVIEW

**Comment by hectorsector** [comment]
Linking to your original issue #12

**Comment by rbowser5** [comment]
It looks nice! I love the way the buttons are shaded. I agree with @hectorsector , adding it to Github Pages would make it a breeze to access. But other than that good job!

**Comment by Jordan-Hosein** [comment]
When I got to it, it looked really nice, even messed around with it to do some of my math homework! Good job!

**Comment by Jomarm92x** [comment]
@hectorsector so I cited my work and put my project in the devel folder. I tried making a site like you said but I'm not sure if I did it correctly: https://github.com/Jomarm92x/Final-Project.git

**Comment by hectorsector** [comment]
@Jomarm92x 👍 great job! Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
