### PR TITLE
Clicheusername Final Project

### PR DESCRIPTION
**Pull request by ClicheUsername**
Ideally my project would have been hosted on Github Pages or similar, however I ran into some issues with http/https compatibility (Good learning experience though)

Any feedback would be great, if anyone gives this a go, please tell me how it works for you, if you find anything broken with it, and anything you think I could improve on. I decided against including historical data as it just seemed impractical for what I was going for with the project.

Also if anyone has any questions about how I did something, feel free to ask, I'm happy to share. 

Suggestions on how I could make it look better would be appreciated as well!

### CODE REVIEW

**Comment by lminks** [comment]
Works just as advertised. Interestingly enough, changing cities doesn't work if you press the enter key, but it does if you click the submit button. I don't claim to know why, though.

**Comment by Mikedaris94** [comment]
Wow Works Great man! I NEED to get better but hey GREAT JOB!

**Comment by AGuerraDumas** [comment]
Wow, this is amazing, it's very clean and functions really well. 10/10.

**Comment by ClicheUsername** [comment]
@lminks I use "OnClick=GetData()" on the button element so it will only call the function to get new weather data from clicking the button rather than hitting enter, but that's something I could probably fix fairly easily.

**Comment by mariadodoll** [comment]
Great job with your project everything works great.

**Comment by jriosrodriguez** [comment]
Excellent work for such a project. The programs runs excellently. I bet in the future you'll be making even greater things. Good stuff!

**Comment by hectorsector** [comment]
Amazing job, @ClicheUsername! This was a fantastic final project and, with your permission, I'd ❤️ to showcase it to future students. 

Now that the project has been graded and the grade has been updated on blackboard, I am closing your Issue and Pull Request. Please email me directly if you have any further questions.

**Pull request closed without merging**
